//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconomicData
    {
        public int DataID { get; set; }
        public int RegionID { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> GDP { get; set; }
        public Nullable<decimal> UnemploymentRate { get; set; }
        public Nullable<decimal> AverageSalary { get; set; }
        public Nullable<decimal> InflationRate { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
