//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int ReportDataID { get; set; }
        public int ReportID { get; set; }
        public string DataType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string TextValue { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Report Report { get; set; }
    }
}
